apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

# Labels comunes para todos los recursos
commonLabels:
  app: portal-facturacion
  managed-by: kustomize

# Imágenes (puedes sobrescribir la imagen aquí)
images:
  - name: portal-facturacion
    newName: portal-facturacion
    newTag: latest
