apiVersion: v1
kind: Secret
metadata:
  name: portal-facturacion-secret
  namespace: default
  labels:
    app: portal-facturacion
type: Opaque
stringData:
  # Flask Secret Key (sin base64, Kubernetes lo codifica automáticamente)
  SECRET_KEY: "dev-secret-key-cambiar-en-produccion-12345678"

  # PostgreSQL Password
  POSTGRES_PASSWORD: "Sergio55"

  # Odoo Password
  ODOO_PASSWORD: "Sergio55"

# NOTA: Para producción, genera los secrets desde el archivo .env usando:
# kubectl create secret generic portal-facturacion-secret \
#   --from-literal=SECRET_KEY="tu-secret-key" \
#   --from-literal=POSTGRES_PASSWORD="tu-password" \
#   --from-literal=ODOO_PASSWORD="tu-password" \
#   --namespace=facturacion

# O desde archivo .env:
# kubectl create secret generic portal-facturacion-secret \
#   --from-env-file=../.env \
#   --namespace=facturacion
